import { useCallback } from "react";
import type { backendInterface } from "../backend";
import { useActor } from "./useActor";

const STORAGE_PREFIX = "pbv_panel_layout_";

// Debounce window for the BACKEND save. localStorage stays instant (the cache);
// the backend blob is written this long after the last drag/fold change.
export const BACKEND_SAVE_DEBOUNCE_MS = 1500;

export interface PanelState {
  x: number;
  y: number;
  folded: boolean;
}

type LayoutMap = Record<string, PanelState>;

/**
 * Extended actor interface that includes the two uiLayout endpoints.
 * The generated `backendInterface` (protected, regenerated by bindgen) does not
 * yet expose saveUserUiLayout / getUserUiLayout even though the backend source
 * (main.mo:69, main.mo:86) does. We extend it locally so calls are type-safe
 * (no `any`) and the cast is sound once bindgen catches up — at which point this
 * extension becomes a no-op superset.
 */
export interface UiLayoutActor extends backendInterface {
  getUserUiLayout(): Promise<string>;
  saveUserUiLayout(
    layout: string,
  ): Promise<{ __kind__: "ok"; ok: null } | { __kind__: "err"; err: string }>;
}

function getStorageKey(userId: string): string {
  return STORAGE_PREFIX + (userId || "guest");
}

function readLayout(userId: string): LayoutMap {
  try {
    const raw = localStorage.getItem(getStorageKey(userId));
    if (!raw) return {};
    return JSON.parse(raw) as LayoutMap;
  } catch {
    return {};
  }
}

function writeLayout(userId: string, layout: LayoutMap): void {
  try {
    localStorage.setItem(getStorageKey(userId), JSON.stringify(layout));
  } catch {
    // ignore
  }
}

function getDefaultLayout(panelIds: string[]): Record<string, PanelState> {
  const result: Record<string, PanelState> = {};
  let xOffset = 10;
  for (const id of panelIds) {
    if (id === "stats") {
      result[id] = {
        x:
          typeof window !== "undefined"
            ? Math.max(0, window.innerWidth - 280)
            : 700,
        y: 80,
        folded: false,
      };
    } else {
      result[id] = { x: xOffset, y: 60, folded: true };
      xOffset += 160;
    }
  }
  return result;
}

function resolveOverlaps(panels: LayoutMap): LayoutMap {
  const result = { ...panels };
  const ids = Object.keys(result);
  for (let i = 0; i < ids.length; i++) {
    for (let j = i + 1; j < ids.length; j++) {
      const a = result[ids[i]];
      const b = result[ids[j]];
      const aw = (a as PanelState & { width?: number }).width ?? 200;
      const ah = (a as PanelState & { height?: number }).height ?? 150;
      const bw = (b as PanelState & { width?: number }).width ?? 200;
      const bh = (b as PanelState & { height?: number }).height ?? 150;
      const overlapX = Math.max(
        0,
        Math.min(a.x + aw, b.x + bw) - Math.max(a.x, b.x),
      );
      const overlapY = Math.max(
        0,
        Math.min(a.y + ah, b.y + bh) - Math.max(a.y, b.y),
      );
      if (overlapX > 0 && overlapY > 0) {
        if (overlapX < overlapY) {
          result[ids[j]] = { ...b, x: a.x + aw + 4 };
        } else {
          result[ids[j]] = { ...b, y: a.y + ah + 4 };
        }
      }
    }
  }
  return result;
}

/**
 * Parse a compact JSON layout blob coming from the backend into a LayoutMap.
 * Returns null if the blob is empty or cannot be parsed/validated, so the
 * caller falls back to localStorage / defaults.
 *
 * Compact JSON format (single Text field, no pretty-printing):
 *   {"stats":{"x":100,"y":50,"folded":false},"spellbook":{"x":10,"y":60,"folded":true}}
 */
function parseBackendLayout(blob: string): LayoutMap | null {
  if (!blob) return null;
  try {
    const parsed = JSON.parse(blob) as unknown;
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      Array.isArray(parsed)
    ) {
      return null;
    }
    const result: LayoutMap = {};
    for (const [id, entry] of Object.entries(
      parsed as Record<string, unknown>,
    )) {
      if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
        continue;
      }
      const e = entry as Record<string, unknown>;
      if (
        typeof e.x !== "number" ||
        typeof e.y !== "number" ||
        typeof e.folded !== "boolean"
      ) {
        continue;
      }
      result[id] = { x: e.x, y: e.y, folded: e.folded };
    }
    return Object.keys(result).length > 0 ? result : null;
  } catch {
    return null;
  }
}

/**
 * Serialize the full panel layout into ONE compact JSON Text field for the
 * backend blob. No pretty-printing — single line, minimal separators.
 */
function serializeLayout(layout: LayoutMap): string {
  return JSON.stringify(layout);
}

/**
 * Load the panel layout from the backend (authoritative on relogin / fresh
 * device). Returns null if the backend is empty, the actor is unavailable, or
 * the call/parse fails — caller then falls back to localStorage / defaults.
 *
 * Never throws: a missing actor (not signed in) or a network failure is a
 * graceful no-op so the localStorage cache path remains usable.
 */
async function loadLayoutFromBackend(
  actor: backendInterface | null,
): Promise<LayoutMap | null> {
  if (!actor) return null;
  try {
    const blob = await (actor as UiLayoutActor).getUserUiLayout();
    return parseBackendLayout(blob);
  } catch (err) {
    console.warn(
      "usePanelLayout: getUserUiLayout failed, falling back to localStorage",
      err,
    );
    return null;
  }
}

/**
 * Save the full panel layout to the backend as one compact JSON Text field.
 * Logs a warning on failure but does NOT throw — the localStorage cache is
 * still valid and the next debounced save will retry.
 */
async function saveLayoutToBackend(
  actor: backendInterface | null,
  layout: LayoutMap,
): Promise<void> {
  if (!actor) return;
  try {
    const result = await (actor as UiLayoutActor).saveUserUiLayout(
      serializeLayout(layout),
    );
    if (result.__kind__ === "err") {
      console.warn("usePanelLayout: saveUserUiLayout rejected:", result.err);
    }
  } catch (err) {
    console.warn(
      "usePanelLayout: saveUserUiLayout failed (localStorage cache still valid)",
      err,
    );
  }
}

export function usePanelLayout(userId: string, panelIds?: string[]) {
  const { actor } = useActor();

  /**
   * Synchronous read of the localStorage cache. Used by getPanelState during
   * the first render (before the backend fetch resolves) so panels paint
   * instantly at their last-known position.
   */
  const getOrInitLayout = useCallback((): LayoutMap => {
    const layout = readLayout(userId);
    if (Object.keys(layout).length === 0 && panelIds && panelIds.length > 0) {
      const defaults = getDefaultLayout(panelIds);
      writeLayout(userId, defaults);
      return defaults;
    }
    return layout;
  }, [userId, panelIds]);

  /**
   * Backend-first login init. Awaits the backend blob; if present, applies it
   * AND writes it to localStorage so the cache stays in sync. If the backend
   * is empty / fails, falls back to localStorage, then defaults. The backend is
   * authoritative on relogin / fresh device.
   *
   * Returns the resolved layout (always non-null — defaults are produced when
   * both backend and localStorage are empty and panelIds were provided).
   */
  const initLayoutFromBackend = useCallback(async (): Promise<LayoutMap> => {
    const backendLayout = await loadLayoutFromBackend(actor);
    if (backendLayout) {
      // Backend authoritative — refresh the localStorage cache to match.
      writeLayout(userId, backendLayout);
      return backendLayout;
    }
    // Backend empty / unavailable — fall back to localStorage, then defaults.
    const local = readLayout(userId);
    if (Object.keys(local).length > 0) return local;
    if (panelIds && panelIds.length > 0) {
      const defaults = getDefaultLayout(panelIds);
      writeLayout(userId, defaults);
      return defaults;
    }
    return {};
  }, [actor, userId, panelIds]);

  const getPanelState = useCallback(
    (panelId: string): PanelState | null => {
      const layout = getOrInitLayout();
      return layout[panelId] ?? null;
    },
    [getOrInitLayout],
  );

  const setPanelState = useCallback(
    (panelId: string, state: PanelState): void => {
      const layout = readLayout(userId);
      layout[panelId] = state;
      const resolved = resolveOverlaps(layout);
      writeLayout(userId, resolved);
    },
    [userId],
  );

  const savePanelState = useCallback(
    (panelId: string, partial: Partial<PanelState>): void => {
      const layout = readLayout(userId);
      const existing = layout[panelId] ?? { x: 0, y: 0, folded: false };
      layout[panelId] = { ...existing, ...partial };
      const resolved = resolveOverlaps(layout);
      writeLayout(userId, resolved);
    },
    [userId],
  );

  const removePanelState = useCallback(
    (panelId: string): void => {
      const layout = readLayout(userId);
      if (layout[panelId]) {
        delete layout[panelId];
        writeLayout(userId, layout);
      }
    },
    [userId],
  );

  return {
    getPanelState,
    setPanelState,
    savePanelState,
    removePanelState,
    initLayoutFromBackend,
    saveLayoutToBackend: (layout: LayoutMap) =>
      saveLayoutToBackend(actor, layout),
    BACKEND_SAVE_DEBOUNCE_MS,
  };
}
