/**
 * bossDefaults.ts — Default BossConfig definitions for all 12 bosses.
 * These are the initial values used before any admin edits are saved.
 * Stored in localStorage under pbv_boss_configs.
 */

import type { BossConfig } from "./bossTypes";
import { BossAbility } from "./bossTypes";

export const DEFAULT_BOSS_CONFIGS: BossConfig[] = [
  {
    id: "pale_archbishop",
    name: "The Pale Archbishop",
    pieceType: "bishop",
    iconEmoji: "📿",
    loreText:
      "A towering bishop draped in rotting vestments, whose very gaze curses all who oppose him.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(35% 0.05 270)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 350,
      ap: 6,
      mp: 4,
      atk: 35,
      res: 12,
      sp: 10,
      init: 8,
      chc: 5,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.CURSE_ON_HIT],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.4,
      spellPoolIds: [],
      specialAbilities: [BossAbility.REFLECT_SHIELD, BossAbility.SPAWN_MINIONS],
      summonCount: 2,
    },
  },
  {
    id: "crimson_countess",
    name: "Crimson Countess",
    pieceType: "rook",
    iconEmoji: "🌹",
    loreText:
      "A rook wearing a crown of blood roses, leaving rivers of lava wherever she travels.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(35% 0.06 20)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 400,
      ap: 5,
      mp: 5,
      atk: 40,
      res: 15,
      sp: 8,
      init: 9,
      chc: 4,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.4,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.5,
      spellPoolIds: [],
      specialAbilities: [BossAbility.LAVA_TRAIL],
      summonCount: 0,
    },
  },
  {
    id: "void_grandmaster",
    name: "The Void Grandmaster",
    pieceType: "king",
    iconEmoji: "♟️",
    loreText:
      "A king piece that flickers between dimensions, splitting into illusions to confuse attackers.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(30% 0.08 260)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 300,
      ap: 7,
      mp: 6,
      atk: 30,
      res: 10,
      sp: 12,
      init: 12,
      chc: 6,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.6,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.TELEPORT_ADJACENT],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.3,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.ILLUSION_SPLIT,
        BossAbility.TELEPORT_ADJACENT,
      ],
      summonCount: 3,
    },
  },
  {
    id: "bone_cavalier",
    name: "Bone Cavalier",
    pieceType: "knight",
    iconEmoji: "🦴",
    loreText:
      "A knight made of fused skeleton parts that leaps through walls ignoring all obstacles.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(38% 0.04 80)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 320,
      ap: 6,
      mp: 4,
      atk: 45,
      res: 8,
      sp: 6,
      init: 11,
      chc: 7,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.KNIGHT_JUMP_IGNORE_WALLS],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.6,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.KNIGHT_JUMP_IGNORE_WALLS,
        BossAbility.SPIKE_ON_LAND,
      ],
      summonCount: 0,
    },
  },
  {
    id: "weeping_pawn",
    name: "The Weeping Pawn",
    pieceType: "pawn",
    iconEmoji: "😭",
    loreText:
      "A giant grotesque pawn that wails endlessly, promoting to a deadly queen at low HP.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(35% 0.07 300)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 500,
      ap: 4,
      mp: 3,
      atk: 25,
      res: 20,
      sp: 8,
      init: 5,
      chc: 3,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.3,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.CURSE_ON_HIT],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 2.0,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.PROMOTE_QUEEN,
        BossAbility.ATTACK_ALL_LINES,
      ],
      summonCount: 0,
    },
  },
  {
    id: "starborn_queen",
    name: "Starborn Queen",
    pieceType: "queen",
    iconEmoji: "⭐",
    loreText:
      "A queen whose body is a swirling galaxy, attacking all lines and filling the field with void.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(30% 0.1 240)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 380,
      ap: 8,
      mp: 7,
      atk: 38,
      res: 14,
      sp: 14,
      init: 10,
      chc: 5,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.ATTACK_ALL_LINES],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.5,
      spellPoolIds: [],
      specialAbilities: [BossAbility.ATTACK_ALL_LINES, BossAbility.VOID_TILES],
      summonCount: 0,
    },
  },
  {
    id: "fetid_rook",
    name: "The Fetid Rook",
    pieceType: "rook",
    iconEmoji: "🧟",
    loreText:
      "A rook of rotting flesh whose every blow stacks compounding rot, splitting into twins at half HP.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(32% 0.06 150)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 420,
      ap: 5,
      mp: 4,
      atk: 32,
      res: 18,
      sp: 10,
      init: 7,
      chc: 4,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.4,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.COMPOUNDING_ROT],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.SPLIT_ROOKS, BossAbility.COMPOUNDING_ROT],
      summonCount: 2,
    },
  },
  {
    id: "eternal_pawn_king",
    name: "Eternal Pawn King",
    pieceType: "pawn",
    iconEmoji: "👑",
    loreText:
      "A pawn that has advanced for centuries — now both pawn and king, draining AP as it advances.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(36% 0.05 60)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 450,
      ap: 6,
      mp: 5,
      atk: 30,
      res: 22,
      sp: 8,
      init: 6,
      chc: 3,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.ADVANCE_PER_TURN],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.3,
      spellPoolIds: [],
      specialAbilities: [BossAbility.AP_DRAIN, BossAbility.ADVANCE_PER_TURN],
      summonCount: 0,
    },
  },
  {
    id: "midnight_bishop",
    name: "Midnight Bishop",
    pieceType: "bishop",
    iconEmoji: "🌑",
    loreText:
      "Twin bishops sharing one HP pool, flanking from both diagonals until they merge into one unstoppable form.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(28% 0.09 270)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 360,
      ap: 6,
      mp: 5,
      atk: 28,
      res: 10,
      sp: 16,
      init: 10,
      chc: 5,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.25,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.TWIN_FLANK],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 2.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.MERGE_BISHOPS, BossAbility.MAGIC_REFLECT],
      summonCount: 0,
    },
  },
  {
    id: "broodmother_rook",
    name: "Broodmother Rook",
    pieceType: "rook",
    iconEmoji: "🪲",
    loreText:
      "A rook hollow with crawling larvae — shell armor activates while they live, and they explode on contact.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(34% 0.08 130)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 480,
      ap: 5,
      mp: 4,
      atk: 28,
      res: 25,
      sp: 6,
      init: 7,
      chc: 3,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.LARVAE_SPAWN, BossAbility.SHELL_ARMOR],
      summonCount: 1,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.4,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.LARVAE_SPAWN,
        BossAbility.SHELL_ARMOR,
        BossAbility.LARVAE_EXPLODE,
      ],
      summonCount: 2,
    },
  },
  {
    id: "lord_of_static",
    name: "Lord of Static",
    pieceType: "king",
    iconEmoji: "⚡",
    loreText:
      "A king crackling with electricity, leaving shock tiles on every move that chain into lightning in phase 2.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(33% 0.07 200)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 340,
      ap: 7,
      mp: 5,
      atk: 35,
      res: 10,
      sp: 12,
      init: 13,
      chc: 6,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.4,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.SHOCK_TILES],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.5,
      spellPoolIds: [],
      specialAbilities: [BossAbility.SHOCK_TILES, BossAbility.CHAIN_LIGHTNING],
      summonCount: 0,
    },
  },
  {
    id: "final_pawn",
    name: "The Final Pawn",
    pieceType: "pawn",
    iconEmoji: "♟",
    loreText:
      "An ordinary-looking pawn that becomes invincible at 1 HP, summoning all 11 ghost bosses at once.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(25% 0.03 0)",
    rewardDokaMultiplier: 10,
    rewardXpMultiplier: 5,
    baseStats: {
      hp: 600,
      ap: 3,
      mp: 2,
      atk: 15,
      res: 5,
      sp: 5,
      init: 4,
      chc: 2,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.1,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 999,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.INVINCIBLE_PHASE,
        BossAbility.GHOST_SUMMON,
      ],
      summonCount: 11,
    },
  },

  // ── Boss 13: The Alabaster Fortress ──────────────────────────────────
  {
    id: "alabaster_fortress",
    name: "The Alabaster Fortress",
    pieceType: "pawn",
    iconEmoji: "🏛️",
    loreText:
      "A colossal pawn of layered white stone slabs, cracked and bleeding dark red between the seams.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(90% 0.02 80)",
    rewardDokaMultiplier: 6,
    rewardXpMultiplier: 4,
    baseStats: {
      hp: 400,
      ap: 3,
      mp: 1,
      atk: 10,
      res: 60,
      sp: 40,
      init: 2,
      chc: 2,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.3,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.RESONANCE_SHOCKWAVE],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.2,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.BOARD_SHRINK,
        BossAbility.RESONANCE_SHOCKWAVE,
      ],
      summonCount: 0,
    },
  },

  // ── Boss 14: The Chessboard Lich ────────────────────────────────
  {
    id: "chessboard_lich",
    name: "The Chessboard Lich",
    pieceType: "king",
    iconEmoji: "💀",
    loreText:
      "A translucent skeletal figure on a floating throne whose very presence rearranges the battlefield.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(55% 0.08 210)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 200,
      ap: 6,
      mp: 8,
      atk: 25,
      res: 8,
      sp: 45,
      init: 30,
      chc: 8,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.MAP_ROTATE],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.3,
      spellPoolIds: [],
      specialAbilities: [BossAbility.MIRROR_INVERT, BossAbility.BOARD_CLAIM],
      summonCount: 0,
    },
  },

  // ── Boss 16: The Mirror Sovereign ───────────────────────────────
  {
    id: "mirror_sovereign",
    name: "The Mirror Sovereign",
    pieceType: "queen",
    iconEmoji: "🪞",
    loreText:
      "A queen of black mirror glass that reflects a distorted version of you — and turns your own spells against you.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(15% 0.03 270)",
    rewardDokaMultiplier: 6,
    rewardXpMultiplier: 4,
    baseStats: {
      hp: 250,
      ap: 8,
      mp: 6,
      atk: 20,
      res: 25,
      sp: 25,
      init: 15,
      chc: 6,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.5,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.SPELL_MIRROR],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.5,
      spellPoolIds: [],
      specialAbilities: [BossAbility.SPELL_MIRROR, BossAbility.COMBO_REPLAY],
      summonCount: 0,
    },
  },

  // ── Boss 17: The Starved Vampire Pawn ──────────────────────────
  {
    id: "starved_vampire_pawn",
    name: "The Starved Vampire Pawn",
    pieceType: "pawn",
    iconEmoji: "🧛",
    loreText:
      "An emaciated chalk-white pawn whose hollow eyes grow brighter with every drop of your blood.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(20% 0.12 15)",
    rewardDokaMultiplier: 5,
    rewardXpMultiplier: 3,
    baseStats: {
      hp: 60,
      ap: 4,
      mp: 3,
      atk: 8,
      res: 5,
      sp: 5,
      init: 15,
      chc: 5,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.01,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.LIFE_DRAIN],
      summonCount: 0,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.VAMPIRIC_AOE,
        BossAbility.EXSANGUINATED_DEBUFF,
        BossAbility.LIFE_DRAIN,
      ],
      summonCount: 0,
    },
  },

  // ── Boss 18: The Pale Archivist ─────────────────────────────────
  {
    id: "pale_archivist",
    name: "The Pale Archivist",
    pieceType: "rook",
    iconEmoji: "📜",
    loreText:
      "A gothic library tower of ivory stone whose orbiting scrolls fight on their own terms.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(95% 0.01 80)",
    rewardDokaMultiplier: 6,
    rewardXpMultiplier: 4,
    baseStats: {
      hp: 350,
      ap: 5,
      mp: 3,
      atk: 18,
      res: 20,
      sp: 15,
      init: 10,
      chc: 4,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.4,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.INK_VEIL,
        BossAbility.SCROLL_SUMMON,
        BossAbility.GLYPH_TRAP,
      ],
      summonCount: 3,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.2,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.PAGES_OF_DOOM,
        BossAbility.INK_VEIL,
        BossAbility.GLYPH_TRAP,
      ],
      summonCount: 2,
    },
  },

  // ── Boss 19: The Twin Monarchs of Dusk and Dawn ────────────────────
  {
    id: "twin_monarchs",
    name: "The Twin Monarchs",
    pieceType: "king",
    iconEmoji: "☯️",
    loreText:
      "Two kings linked by a cord of light — golden Dawn and silver Dusk — sharing one destiny.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(18% 0.06 260)",
    rewardDokaMultiplier: 7,
    rewardXpMultiplier: 5,
    baseStats: {
      hp: 300,
      ap: 6,
      mp: 4,
      atk: 22,
      res: 18,
      sp: 12,
      init: 20,
      chc: 5,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.01,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [BossAbility.DAWN_BUFF, BossAbility.DUSK_DOT],
      summonCount: 1,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.4,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.MONARCH_ABSORB,
        BossAbility.DAWN_BUFF,
        BossAbility.DUSK_DOT,
      ],
      summonCount: 0,
    },
  },

  // ── Boss 20: The Enthroned Void ──────────────────────────────────
  {
    id: "enthroned_void",
    name: "The Enthroned Void",
    pieceType: "king",
    iconEmoji: "🌑",
    loreText:
      "An empty throne surrounded by creeping black mist. Destroy eight anchor tiles to make it vulnerable.",
    portalColor: "#9333ea",
    bossMapColor: "oklch(8% 0.04 270)",
    rewardDokaMultiplier: 8,
    rewardXpMultiplier: 6,
    baseStats: {
      hp: 280,
      ap: 7,
      mp: 4,
      atk: 35,
      res: 15,
      sp: 20,
      init: 18,
      chc: 6,
    },
    phase1: {
      phaseNumber: 1,
      hpThreshold: 0.01,
      statMultiplier: 1.0,
      spellPoolIds: [],
      specialAbilities: [
        BossAbility.DAMAGE_IMMUNE,
        BossAbility.ANCHOR_TILES,
        BossAbility.PHANTOM_SPAWN,
      ],
      summonCount: 2,
    },
    phase2: {
      phaseNumber: 2,
      hpThreshold: 0.0,
      statMultiplier: 1.6,
      spellPoolIds: [],
      specialAbilities: [BossAbility.AP_DRAIN_PASSIVE],
      summonCount: 0,
    },
  },
];

export function getDefaultBossConfig(id: string): BossConfig | undefined {
  return DEFAULT_BOSS_CONFIGS.find((b) => b.id === id);
}
