/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AchievementConfig {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'dokaReward' : bigint,
  'condition' : string,
}
export interface AchievementProgress {
  'achievementId' : string,
  'unlockedAt' : bigint,
  'unlocked' : boolean,
  'claimed' : boolean,
  'principalId' : string,
}
export interface AdminGameConfig {
  'leaderBoostPercent' : bigint,
  'dokaSpawnBaseValue' : bigint,
  'dokaSpawnChance' : bigint,
}
export interface BattleEffect {
  'id' : string,
  'value' : bigint,
  'name' : string,
  'description' : string,
  'effectType' : { 'damage' : null } |
    { 'buff' : null } |
    { 'debuff' : null },
}
export interface BossConfig {
  'id' : string,
  'pieceType' : string,
  'name' : string,
  'portalColor' : string,
  'baseStats' : BossStats,
  'rewardXpMultiplier' : number,
  'bossMapColor' : string,
  'adminNotes' : string,
  'rewardDokaMultiplier' : number,
  'phase1' : BossPhaseConfig,
  'phase2' : BossPhaseConfig,
  'defeated' : boolean,
}
export interface BossPhaseConfig {
  'hpThreshold' : number,
  'statMultiplier' : number,
  'phaseNumber' : bigint,
  'spellPoolIds' : Array<string>,
  'specialAbilities' : Array<string>,
  'summonCount' : bigint,
}
export interface BossStats {
  'ap' : bigint,
  'hp' : bigint,
  'mp' : bigint,
  'sp' : bigint,
  'atk' : bigint,
  'res' : bigint,
  'init' : bigint,
}
export type BuffInventory = Array<BuffInventoryItem>;
export interface BuffInventoryItem { 'itemId' : string, 'quantity' : bigint }
export interface Cell { 'value' : Value, 'name' : string }
export interface Character {
  'rotation' : bigint,
  'activeSpells' : [] | [Array<bigint>],
  'pieceType' : string,
  'name' : string,
  'covenantBuff' : [] | [string],
  'level' : bigint,
  'experience' : bigint,
  'stats' : CharacterStats,
  'spellLevelKeys' : Array<string>,
  'shrineCount' : [] | [bigint],
  'spellLevelValues' : Array<bigint>,
  'bloodBalance' : [] | [bigint],
  'bossRushMasterComplete' : [] | [boolean],
  'colors' : Array<string>,
  'pixelPattern' : string,
}
export type CharacterSlot = [] | [Character];
export interface CharacterSlots {
  'slot1' : CharacterSlot,
  'slot2' : CharacterSlot,
  'slot3' : CharacterSlot,
}
export interface CharacterStats {
  'ap' : bigint,
  'hp' : bigint,
  'mp' : bigint,
  'sp' : bigint,
  'sr' : bigint,
  'atk' : bigint,
  'chc' : bigint,
  'res' : bigint,
  'killCount' : bigint,
  'init' : bigint,
  'resilience' : bigint,
  'evasion' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'colorHex' : string,
  'playerName' : string,
  'timestampMs' : bigint,
}
export interface DungeonRecord {
  'chainDepth' : bigint,
  'totalMapsCompleted' : bigint,
  'bestRewardMultiplier' : number,
}
export interface EnemyConfig {
  'ap' : bigint,
  'hp' : bigint,
  'id' : string,
  'mp' : bigint,
  'levelMax' : bigint,
  'levelMin' : bigint,
  'name' : string,
  'initStat' : bigint,
  'spriteUrl' : [] | [string],
  'regions' : Array<string>,
}
export interface LevelUpConfig {
  'spellLevelingCostMultiplier' : number,
  'spellLevelingBaseCost' : bigint,
  'spellFailBaseChance' : number,
  'maxSpellRange' : bigint,
  'spellFailReductionPerLevel' : number,
  'spellRangeGrowthLevels' : bigint,
  'statGrowthPercent' : bigint,
  'spellDmgGrowthPercent' : bigint,
  'apMpLevelThreshold' : bigint,
}
export interface MapModifierConfig {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'modifierType' : string,
  'triggerChance' : bigint,
}
export interface PlayerSpriteConfig {
  'id' : string,
  'rightWalkFrames' : Array<string>,
  'name' : string,
  'frontUrl' : [] | [string],
  'frontWalkFrames' : Array<string>,
  'characterPieceType' : string,
  'rightUrl' : [] | [string],
  'leftWalkFrames' : Array<string>,
  'backWalkFrames' : Array<string>,
  'leftUrl' : [] | [string],
  'backUrl' : [] | [string],
}
export interface PurchaseRecord {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'customerCountry' : string,
  'dokaAmount' : bigint,
  'customerSurname' : string,
  'customerPostal' : string,
  'customerAddress' : string,
  'proofFileUrl' : string,
  'userPrincipal' : Principal,
  'timestamp' : bigint,
  'customerEmail' : string,
  'packageId' : string,
  'customerCity' : string,
}
export interface RegionConfig {
  'id' : string,
  'backgroundColor' : string,
  'levelMax' : bigint,
  'levelMin' : bigint,
  'name' : string,
  'battleEffects' : Array<BattleEffect>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ShopPackage {
  'id' : string,
  'displayOrder' : bigint,
  'dokaAmount' : bigint,
  'priceEuroCents' : bigint,
  'paymentLink' : string,
}
export interface SpellConfig {
  'id' : string,
  'aoe' : boolean,
  'effectCategory' : string,
  'damage' : bigint,
  'lineOfSight' : boolean,
  'freeCells' : boolean,
  'effectParams' : [] | [string],
  'mpCost' : bigint,
  'isPhysical' : boolean,
  'name' : string,
  'hitTiles' : Array<[bigint, bigint]>,
  'description' : string,
  'minLevel' : bigint,
  'apCost' : bigint,
  'multiTarget' : boolean,
  'modifiableRange' : boolean,
  'usableByEnemy' : boolean,
  'maxRange' : bigint,
  'healAmount' : bigint,
  'iconEmoji' : string,
  'hitsAllies' : boolean,
  'effectType' : string,
  'usableByPlayer' : boolean,
  'spellType' : string,
  'diagonal' : boolean,
  'minRange' : bigint,
  'range' : bigint,
  'linear' : boolean,
  'cooldown' : bigint,
}
export interface TierSpawnConfig {
  'adjacentTierPercent' : number,
  'tierSize' : bigint,
  'sameTierPercent' : number,
  'twoAwayPercent' : number,
  'threeOrMorePercent' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  /**
   * / Adds a new name to the pool (admin only).
   */
  'addEnemyName' : ActorMethod<[string], undefined>,
  /**
   * / Admin: add Doka to any account (used by shop admin panel to manually credit Doka).
   */
  'adminAddDoka' : ActorMethod<
    [Principal, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: manually credit Doka to a principal and optionally mark a purchase as completed.
   */
  'adminAddDokaToUser' : ActorMethod<
    [Principal, bigint, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: ban a principal for non-payment.
   * / M2: also clears achievement progress so banned players cannot double-claim
   * /     Doka rewards after being unbanned.
   */
  'adminBanAccount' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: clear a specific ad box slot (sets it back to empty/inactive).
   */
  'adminClearAdBox' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: delete an achievement configuration.
   */
  'adminDeleteAchievementConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteEnemyConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteMapModifier' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeletePlayerSpriteConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteRegionConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: delete a shop package.
   */
  'adminDeleteShopPackage' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteSpellConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: get the Doka balance of any account.
   */
  'adminGetDoka' : ActorMethod<
    [Principal],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Admin: get all purchase records, optionally filtered by principal text.
   */
  'adminGetPurchaseRecords' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<PurchaseRecord> } |
      { 'err' : string }
  >,
  /**
   * / Admin: grant Doka to a principal by text ID (used by shop admin panel).
   * / Alias for adminAddDoka; named adminGrantDoka to match the frontend's expected method name.
   */
  'adminGrantDoka' : ActorMethod<
    [Principal, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: create or update an achievement configuration.
   */
  'adminSetAchievementConfig' : ActorMethod<
    [AchievementConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: set the image URL and link URL for a specific ad box slot.
   * / index must be 0, 1, or 2; the slot is immediately marked active.
   */
  'adminSetAdBox' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetBossRushConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetColorPalette' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetEnemyConfig' : ActorMethod<
    [EnemyConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetGameConfig' : ActorMethod<
    [AdminGameConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetLevelUpConfig' : ActorMethod<
    [LevelUpConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetMapModifier' : ActorMethod<
    [MapModifierConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Convenience endpoint: update only the triggerChance of an existing map modifier.
   * / Validates that chance is in the range 0–100.
   */
  'adminSetMapModifierChance' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetPlayerSpriteConfig' : ActorMethod<
    [PlayerSpriteConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetRegionConfig' : ActorMethod<
    [RegionConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: create or update a shop package (set payment link etc.).
   */
  'adminSetShopPackage' : ActorMethod<
    [ShopPackage],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetSpellConfig' : ActorMethod<
    [SpellConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetTierSpawnConfig' : ActorMethod<
    [TierSpawnConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: unban a principal.
   */
  'adminUnbanAccount' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'applyRewards' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : { 'newLevel' : bigint, 'newXp' : bigint, 'newDoka' : bigint } } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: assign a role to another principal.
   * / M1: rate-limited — the same caller cannot change roles more than once per 30 s.
   */
  'assignUserRole' : ActorMethod<
    [Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: ban a player with a reason (convenience alias for adminBanAccount with reason).
   * / M2: also clears achievement progress so banned players cannot double-claim on unban.
   */
  'banPlayer' : ActorMethod<
    [Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: ban a principal (simple alias matching the frontend's expected method name).
   */
  'banPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / For each enemy in the list, computes a Doka drop using true IC randomness,
   * / sums the drops, adds to the caller's balance, and returns the total earned.
   * /
   * / Tier probabilities (out of 10_000 units):
   * /   9000 / 10000 = 90%   → 1–3
   * /    500 / 10000 =  5%   → 1–10
   * /    300 / 10000 =  3%   → 1–50
   * /    100 / 10000 =  1%   → 55–100
   * /     50 / 10000 = 0.5%  → 1–1000
   * /     40 / 10000 = 0.4%  → 1–5000
   * /      5 / 10000 = 0.05% → 1–1_000_000
   * /      1 / 10000 = 0.01% (≈ 0.0001%) → 1–1_000_000_000
   * /      4 remaining → 1–50  (lumped with 3% tier)
   */
  'calculateAndAwardDoka' : ActorMethod<[Array<{ 'level' : bigint }>], bigint>,
  /**
   * / Returns whether the caller's account is banned.
   */
  'checkAccountStatus' : ActorMethod<[], { 'isBanned' : boolean }>,
  /**
   * / Player: claim the Doka reward for a completed achievement.
   * / Checks: achievement must be unlocked for this player AND not already claimed.
   * / On success, adds dokaReward to the caller's dokaBalances entry and marks as claimed.
   */
  'claimAchievementReward' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Called when a boss rush room is cleared. Awards Doka and XP to the character.
   * / Room 10 (roomIndex = 9 completed → highestRoomCompleted reaches 10) sets bossRushMasterComplete.
   */
  'completeBossRushRoom' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCharacter' : ActorMethod<
    [bigint, Character],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: delete a boss configuration by id.
   */
  'deleteBossConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: remove a boss portal assignment.
   */
  'deleteBossPortalAssignment' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteCharacter' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Removes a name from the pool by value (admin only).
   */
  'deleteEnemyName' : ActorMethod<[string], undefined>,
  /**
   * / Debug query: returns raw slot data as text for diagnosing serialization issues.
   */
  'diagnoseCharacterSlots' : ActorMethod<[], string>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Public: list all achievement configs (used by frontend to render the achievements panel).
   */
  'getAchievementConfigs' : ActorMethod<[], Array<AchievementConfig>>,
  /**
   * / Returns all three ad box slots.  Empty/inactive slots have isActive=false.
   */
  'getAdBoxes' : ActorMethod<[], Array<[string, string, boolean]>>,
  /**
   * / Public: returns all boss configs.
   */
  'getAllBossConfigs' : ActorMethod<[], Array<BossConfig>>,
  'getAllCharacters' : ActorMethod<
    [],
    { 'ok' : Array<[Principal, CharacterSlots]> } |
      { 'err' : string }
  >,
  /**
   * / Returns the current app version string.
   */
  'getAppVersion' : ActorMethod<[], string>,
  /**
   * / Admin query: returns the list of all currently banned principals.
   */
  'getBannedPrincipals' : ActorMethod<
    [],
    { 'ok' : Array<Principal> } |
      { 'err' : string }
  >,
  /**
   * / Public: returns a single boss config by id (null if not found).
   */
  'getBossConfig' : ActorMethod<[string], [] | [BossConfig]>,
  /**
   * / Public: returns all (portalId, bossId) pairs for active boss portal assignments.
   */
  'getBossPortalAssignments' : ActorMethod<[], Array<[string, string]>>,
  'getBossRushConfig' : ActorMethod<[], string>,
  /**
   * / Returns (currentRoom, highestRoomCompleted, totalBossRushRuns) for any player+slot.
   */
  'getBossRushState' : ActorMethod<
    [Principal, bigint],
    [bigint, bigint, bigint]
  >,
  /**
   * / Public: list all available buff items (itemId, name, dokaCost).
   */
  'getBuffCatalog' : ActorMethod<[], Array<[string, string, bigint]>>,
  /**
   * / Retrieve a character slot's buff inventory.
   */
  'getBuffInventory' : ActorMethod<
    [bigint],
    { 'ok' : BuffInventory } |
      { 'err' : string }
  >,
  /**
   * / Public query: returns the Doka balance for the caller (H1, H5).
   */
  'getCallerDokaBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the changelog text for a given version (null if not set).
   */
  'getChangelog' : ActorMethod<[string], [] | [string]>,
  /**
   * / Returns the version string of the changelog the given user has already seen.
   * / Empty string means the user has not seen any changelog yet.
   */
  'getChangelogShownVersion' : ActorMethod<[Principal], string>,
  'getCharacter' : ActorMethod<[bigint], CharacterSlot>,
  'getCharacterSlots' : ActorMethod<[], CharacterSlots>,
  /**
   * / Retrieve the full Character record for a given slot.
   */
  'getCharacterStats' : ActorMethod<
    [bigint],
    { 'ok' : Character } |
      { 'err' : string }
  >,
  'getColorPalette' : ActorMethod<[], string>,
  /**
   * / Returns the caller's current Doka balance.
   */
  'getDokaBalance' : ActorMethod<[], bigint>,
  /**
   * / Returns a player's current dungeon chain record (null if never entered a dungeon).
   */
  'getDungeonRecord' : ActorMethod<[Principal], [] | [DungeonRecord]>,
  'getEnemyConfigs' : ActorMethod<[], Array<EnemyConfig>>,
  /**
   * / Compute the base HP for an enemy of the given tier at the given player level,
   * / using the admin-configurable stat growth percent as the scaling factor.
   * / Formula: baseHP * (1 + (level * scalingFactor))
   * / where scalingFactor = levelUpConfig.statGrowthPercent / 100.0
   * / and baseHP is determined by tier: tier 1 = 30, +20 per additional tier.
   */
  'getEnemyHPForLevel' : ActorMethod<[bigint, bigint], bigint>,
  /**
   * / Returns the current list of admin-managed enemy names.
   * / When the stored list is empty the canonical ancient names default list
   * / is returned so enemies are never named “AncientOne” by fallback.
   */
  'getEnemyNames' : ActorMethod<[], Array<string>>,
  'getGameConfig' : ActorMethod<[], AdminGameConfig>,
  'getLeaderboard' : ActorMethod<
    [],
    Array<
      {
        'killCount' : bigint,
        'level' : bigint,
        'achievementsCompleted' : bigint,
        'playerName' : string,
        'principalId' : string,
      }
    >
  >,
  'getLevelUpConfig' : ActorMethod<[], LevelUpConfig>,
  'getMapModifiers' : ActorMethod<[], Array<MapModifierConfig>>,
  /**
   * / Returns all current chat messages (oldest first).
   */
  'getMessages' : ActorMethod<[], Array<ChatMessage>>,
  /**
   * / Returns the caller's purchase history.
   */
  'getMyPurchaseHistory' : ActorMethod<[], Array<PurchaseRecord>>,
  /**
   * / Public: return the achievement progress records for the given principal.
   */
  'getPlayerAchievements' : ActorMethod<
    [Principal],
    Array<AchievementProgress>
  >,
  'getPlayerSpriteConfigs' : ActorMethod<[], Array<PlayerSpriteConfig>>,
  /**
   * / Public: returns all purchase records (admin-only; use adminGetPurchaseRecords for filtered access).
   */
  'getPurchases' : ActorMethod<
    [],
    { 'ok' : Array<PurchaseRecord> } |
      { 'err' : string }
  >,
  'getRegionConfigs' : ActorMethod<[], Array<RegionConfig>>,
  /**
   * / Query the persisted session state for a character slot.
   * / Returns null values for any field not yet set (legacy characters).
   */
  'getSessionState' : ActorMethod<
    [bigint],
    {
        'ok' : {
          'activeSpells' : Array<bigint>,
          'covenantBuff' : string,
          'shrineCount' : bigint,
          'bloodBalance' : bigint,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Public: list all shop packages sorted by displayOrder.
   */
  'getShopPackages' : ActorMethod<[], Array<ShopPackage>>,
  /**
   * / Public: returns all (dokaAmount, paymentLink) pairs.
   */
  'getShopPaymentLinks' : ActorMethod<[], Array<[bigint, string]>>,
  'getSpellConfigs' : ActorMethod<[], Array<SpellConfig>>,
  'getTierSpawnConfig' : ActorMethod<[], TierSpawnConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Returns "admin" if the caller has admin permission, otherwise "user".
   * / Triggers first-login admin auto-assignment: the very first principal
   * / to call this becomes admin.
   */
  'getUserRole' : ActorMethod<[], string>,
  /**
   * / Seed the names list on first call if it is empty.
   */
  'initDefaultNames' : ActorMethod<[], undefined>,
  /**
   * / Player initiates a purchase — creates a pending record.
   * / Returns the purchase id so the frontend can track it.
   * / H5: Accepts all customer fields including proofFileUrl.
   */
  'initiatePurchase' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Public query: returns whether a given principal is banned.
   */
  'isPlayerBanned' : ActorMethod<[Principal], boolean>,
  /**
   * / Player: mark an achievement as unlocked (called by the frontend when the condition is met).
   * / Idempotent — calling again on an already-unlocked achievement is a no-op.
   */
  'markAchievementUnlocked' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Called by the frontend after the player dismisses the changelog popup.
   * / Records that the caller has seen the changelog for the given version.
   */
  'markChangelogShown' : ActorMethod<[string], undefined>,
  /**
   * / Player calls this to trigger auto-completion of their pending purchases.
   */
  'processPendingPurchases' : ActorMethod<[], bigint>,
  /**
   * / Purchase a buff item. Deducts Doka from caller's per-principal balance.
   */
  'purchaseBuff' : ActorMethod<
    [bigint, string],
    { 'ok' : BuffInventory } |
      { 'err' : string }
  >,
  /**
   * / Rename a character in the given slot. Costs 100 Doka from the character's balance.
   */
  'renameCharacter' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Called on player death or boss rush abort. Resets currentRoom to 0.
   */
  'resetBossRush' : ActorMethod<[bigint], undefined>,
  /**
   * / Reset a player's dungeon chain (called on death or chain completion).
   */
  'resetDungeonChain' : ActorMethod<[Principal], undefined>,
  /**
   * / Save the active spell loadout (up to 8 spell IDs) for a character slot.
   * / Replaces localStorage so spell loadouts persist across devices and browser clears.
   */
  'saveActiveSpells' : ActorMethod<
    [bigint, Array<bigint>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Save all battle-relevant stats back to a character slot after a battle.
   * / hp may arrive as negative (character was knocked out); it is clamped to 0 before storage.
   * / C1: dokaBalance parameter is intentionally ignored — Doka is tracked in the
   * /     per-principal dokaBalances Map only. The dokaBalance field no longer exists
   * /     on the Character type.
   */
  'saveBattleStats' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<bigint>,
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveKillCount' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Append a new message; trims list to at most 200 entries (oldest dropped).
   */
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Admin-only: sets the current app version string.
   */
  'setAppVersion' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Admin: create or update a boss configuration.
   */
  'setBossConfig' : ActorMethod<
    [BossConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: assign a boss to a portal (or overwrite an existing assignment).
   */
  'setBossPortalAssignment' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Called when the player enters a boss rush room. Records the current room index.
   */
  'setBossRushProgress' : ActorMethod<[bigint, bigint], undefined>,
  /**
   * / Admin-only: sets the changelog text for a given version.
   */
  'setChangelog' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: set the payment URL for a specific shop package by dokaAmount.
   */
  'setShopPaymentLink' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: unban a player account.
   */
  'unbanPlayer' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin: unban a principal (simple alias matching the frontend's expected method name).
   */
  'unbanPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCharacter' : ActorMethod<
    [bigint, Character],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Update a player's dungeon progress (called by the frontend on each map completion).
   */
  'updateDungeonProgress' : ActorMethod<[Principal, bigint], undefined>,
  /**
   * / Update the session state fields (bloodBalance, covenantBuff, shrineCount)
   * / for a character slot. Replaces localStorage for cross-device persistence.
   */
  'updateSessionState' : ActorMethod<
    [bigint, bigint, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Upgrade a spell for the character in the given slot.
   * / Cost = baseCost * 2^currentSpellLevel (all in Doka from character's dokaBalance).
   * / Returns the new spell level on success.
   */
  'upgradeSpell' : ActorMethod<
    [bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Use one of a buff item (removes one from inventory).
   */
  'useBuffItem' : ActorMethod<
    [bigint, string],
    { 'ok' : BuffInventory } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];