/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PurchaseRecord = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerCountry' : IDL.Text,
  'dokaAmount' : IDL.Nat,
  'customerSurname' : IDL.Text,
  'customerPostal' : IDL.Text,
  'customerAddress' : IDL.Text,
  'proofFileUrl' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'customerEmail' : IDL.Text,
  'packageId' : IDL.Text,
  'customerCity' : IDL.Text,
});
export const AchievementConfig = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'dokaReward' : IDL.Nat,
  'condition' : IDL.Text,
});
export const EnemyConfig = IDL.Record({
  'ap' : IDL.Nat,
  'hp' : IDL.Nat,
  'id' : IDL.Text,
  'mp' : IDL.Nat,
  'levelMax' : IDL.Nat,
  'levelMin' : IDL.Nat,
  'name' : IDL.Text,
  'initStat' : IDL.Nat,
  'spriteUrl' : IDL.Opt(IDL.Text),
  'regions' : IDL.Vec(IDL.Text),
});
export const AdminGameConfig = IDL.Record({
  'leaderBoostPercent' : IDL.Nat,
  'dokaSpawnBaseValue' : IDL.Nat,
  'dokaSpawnChance' : IDL.Nat,
});
export const LevelUpConfig = IDL.Record({
  'spellLevelingCostMultiplier' : IDL.Float64,
  'spellLevelingBaseCost' : IDL.Nat,
  'spellFailBaseChance' : IDL.Float64,
  'maxSpellRange' : IDL.Nat,
  'spellFailReductionPerLevel' : IDL.Float64,
  'spellRangeGrowthLevels' : IDL.Nat,
  'statGrowthPercent' : IDL.Nat,
  'spellDmgGrowthPercent' : IDL.Nat,
  'apMpLevelThreshold' : IDL.Nat,
});
export const MapModifierConfig = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'modifierType' : IDL.Text,
  'triggerChance' : IDL.Nat,
});
export const PlayerSpriteConfig = IDL.Record({
  'id' : IDL.Text,
  'rightWalkFrames' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'frontUrl' : IDL.Opt(IDL.Text),
  'frontWalkFrames' : IDL.Vec(IDL.Text),
  'characterPieceType' : IDL.Text,
  'rightUrl' : IDL.Opt(IDL.Text),
  'leftWalkFrames' : IDL.Vec(IDL.Text),
  'backWalkFrames' : IDL.Vec(IDL.Text),
  'leftUrl' : IDL.Opt(IDL.Text),
  'backUrl' : IDL.Opt(IDL.Text),
});
export const BattleEffect = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'effectType' : IDL.Variant({
    'damage' : IDL.Null,
    'buff' : IDL.Null,
    'debuff' : IDL.Null,
  }),
});
export const RegionConfig = IDL.Record({
  'id' : IDL.Text,
  'backgroundColor' : IDL.Text,
  'levelMax' : IDL.Nat,
  'levelMin' : IDL.Nat,
  'name' : IDL.Text,
  'battleEffects' : IDL.Vec(BattleEffect),
});
export const ShopPackage = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'dokaAmount' : IDL.Nat,
  'priceEuroCents' : IDL.Nat,
  'paymentLink' : IDL.Text,
});
export const SpellConfig = IDL.Record({
  'id' : IDL.Text,
  'aoe' : IDL.Bool,
  'effectCategory' : IDL.Text,
  'damage' : IDL.Nat,
  'lineOfSight' : IDL.Bool,
  'freeCells' : IDL.Bool,
  'effectParams' : IDL.Opt(IDL.Text),
  'mpCost' : IDL.Nat,
  'isPhysical' : IDL.Bool,
  'name' : IDL.Text,
  'hitTiles' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
  'description' : IDL.Text,
  'minLevel' : IDL.Nat,
  'apCost' : IDL.Nat,
  'multiTarget' : IDL.Bool,
  'modifiableRange' : IDL.Bool,
  'usableByEnemy' : IDL.Bool,
  'maxRange' : IDL.Nat,
  'healAmount' : IDL.Nat,
  'iconEmoji' : IDL.Text,
  'hitsAllies' : IDL.Bool,
  'effectType' : IDL.Text,
  'usableByPlayer' : IDL.Bool,
  'spellType' : IDL.Text,
  'diagonal' : IDL.Bool,
  'minRange' : IDL.Nat,
  'range' : IDL.Nat,
  'linear' : IDL.Bool,
  'cooldown' : IDL.Nat,
});
export const TierSpawnConfig = IDL.Record({
  'adjacentTierPercent' : IDL.Float64,
  'tierSize' : IDL.Nat,
  'sameTierPercent' : IDL.Float64,
  'twoAwayPercent' : IDL.Float64,
  'threeOrMorePercent' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CharacterStats = IDL.Record({
  'ap' : IDL.Nat,
  'hp' : IDL.Nat,
  'mp' : IDL.Nat,
  'sp' : IDL.Nat,
  'sr' : IDL.Nat,
  'atk' : IDL.Nat,
  'chc' : IDL.Nat,
  'res' : IDL.Nat,
  'killCount' : IDL.Nat,
  'init' : IDL.Nat,
  'resilience' : IDL.Nat,
  'evasion' : IDL.Nat,
});
export const Character = IDL.Record({
  'rotation' : IDL.Nat,
  'activeSpells' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'pieceType' : IDL.Text,
  'name' : IDL.Text,
  'covenantBuff' : IDL.Opt(IDL.Text),
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
  'stats' : CharacterStats,
  'spellLevelKeys' : IDL.Vec(IDL.Text),
  'shrineCount' : IDL.Opt(IDL.Nat),
  'spellLevelValues' : IDL.Vec(IDL.Nat),
  'bloodBalance' : IDL.Opt(IDL.Nat),
  'bossRushMasterComplete' : IDL.Opt(IDL.Bool),
  'colors' : IDL.Vec(IDL.Text),
  'spellBarOrder' : IDL.Opt(IDL.Vec(IDL.Text)),
  'pixelPattern' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const BossStats = IDL.Record({
  'ap' : IDL.Nat,
  'hp' : IDL.Nat,
  'mp' : IDL.Nat,
  'sp' : IDL.Nat,
  'atk' : IDL.Nat,
  'res' : IDL.Nat,
  'init' : IDL.Nat,
});
export const BossPhaseConfig = IDL.Record({
  'hpThreshold' : IDL.Float64,
  'statMultiplier' : IDL.Float64,
  'phaseNumber' : IDL.Nat,
  'spellPoolIds' : IDL.Vec(IDL.Text),
  'specialAbilities' : IDL.Vec(IDL.Text),
  'summonCount' : IDL.Nat,
});
export const BossConfig = IDL.Record({
  'id' : IDL.Text,
  'pieceType' : IDL.Text,
  'name' : IDL.Text,
  'portalColor' : IDL.Text,
  'baseStats' : BossStats,
  'rewardXpMultiplier' : IDL.Float64,
  'bossMapColor' : IDL.Text,
  'adminNotes' : IDL.Text,
  'rewardDokaMultiplier' : IDL.Float64,
  'phase1' : BossPhaseConfig,
  'phase2' : BossPhaseConfig,
  'defeated' : IDL.Bool,
});
export const CharacterSlot = IDL.Opt(Character);
export const CharacterSlots = IDL.Record({
  'slot1' : CharacterSlot,
  'slot2' : CharacterSlot,
  'slot3' : CharacterSlot,
});
export const BuffInventoryItem = IDL.Record({
  'itemId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const BuffInventory = IDL.Vec(BuffInventoryItem);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'uiLayout' : IDL.Text,
});
export const DungeonRecord = IDL.Record({
  'chainDepth' : IDL.Nat,
  'totalMapsCompleted' : IDL.Nat,
  'bestRewardMultiplier' : IDL.Float64,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'colorHex' : IDL.Text,
  'playerName' : IDL.Text,
  'timestampMs' : IDL.Int,
});
export const AchievementProgress = IDL.Record({
  'achievementId' : IDL.Text,
  'unlockedAt' : IDL.Int,
  'unlocked' : IDL.Bool,
  'claimed' : IDL.Bool,
  'principalId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addEnemyName' : IDL.Func([IDL.Text], [], []),
  'adminAddDoka' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAddDokaToUser' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminBanAccount' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminClearAdBox' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteAchievementConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteEnemyConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteMapModifier' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeletePlayerSpriteConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteRegionConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteShopPackage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteSpellConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetDoka' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'adminGetPurchaseRecords' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRecord), 'err' : IDL.Text })],
      [],
    ),
  'adminGrantDoka' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetAchievementConfig' : IDL.Func(
      [AchievementConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetAdBox' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetBossRushConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetColorPalette' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetEnemyConfig' : IDL.Func(
      [EnemyConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetGameConfig' : IDL.Func(
      [AdminGameConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetLevelUpConfig' : IDL.Func(
      [LevelUpConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetMapModifier' : IDL.Func(
      [MapModifierConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetMapModifierChance' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetPlayerSpriteConfig' : IDL.Func(
      [PlayerSpriteConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetRegionConfig' : IDL.Func(
      [RegionConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetShopPackage' : IDL.Func(
      [ShopPackage],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetSpellConfig' : IDL.Func(
      [SpellConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetTierSpawnConfig' : IDL.Func(
      [TierSpawnConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUnbanAccount' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'applyRewards' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'newLevel' : IDL.Nat,
            'newXp' : IDL.Nat,
            'newDoka' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'banPlayer' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'banPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'calculateAndAwardDoka' : IDL.Func(
      [IDL.Vec(IDL.Record({ 'level' : IDL.Nat }))],
      [IDL.Nat],
      [],
    ),
  'checkAccountStatus' : IDL.Func(
      [],
      [IDL.Record({ 'isBanned' : IDL.Bool })],
      ['query'],
    ),
  'claimAchievementReward' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'completeBossRushRoom' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCharacter' : IDL.Func(
      [IDL.Nat, Character],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBossConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBossPortalAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteCharacter' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteEnemyName' : IDL.Func([IDL.Text], [], []),
  'diagnoseCharacterSlots' : IDL.Func([], [IDL.Text], ['query']),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAchievementConfigs' : IDL.Func(
      [],
      [IDL.Vec(AchievementConfig)],
      ['query'],
    ),
  'getAdBoxes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAllBossConfigs' : IDL.Func([], [IDL.Vec(BossConfig)], ['query']),
  'getAllCharacters' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, CharacterSlots)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getBannedPrincipals' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Principal), 'err' : IDL.Text })],
      ['query'],
    ),
  'getBossConfig' : IDL.Func([IDL.Text], [IDL.Opt(BossConfig)], ['query']),
  'getBossPortalAssignments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getBossRushConfig' : IDL.Func([], [IDL.Text], ['query']),
  'getBossRushState' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getBuffCatalog' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getBuffInventory' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerDokaBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangelog' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getChangelogShownVersion' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [CharacterSlot], ['query']),
  'getCharacterSlots' : IDL.Func([], [CharacterSlots], ['query']),
  'getCharacterStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : Character, 'err' : IDL.Text })],
      ['query'],
    ),
  'getColorPalette' : IDL.Func([], [IDL.Text], ['query']),
  'getDokaBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDungeonRecord' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DungeonRecord)],
      ['query'],
    ),
  'getEnemyConfigs' : IDL.Func([], [IDL.Vec(EnemyConfig)], ['query']),
  'getEnemyHPForLevel' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getEnemyNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getGameConfig' : IDL.Func([], [AdminGameConfig], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'killCount' : IDL.Nat,
            'level' : IDL.Nat,
            'achievementsCompleted' : IDL.Nat,
            'playerName' : IDL.Text,
            'principalId' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getLevelUpConfig' : IDL.Func([], [LevelUpConfig], ['query']),
  'getMapModifiers' : IDL.Func([], [IDL.Vec(MapModifierConfig)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMyPurchaseHistory' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getPlayerAchievements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AchievementProgress)],
      ['query'],
    ),
  'getPlayerSpriteConfigs' : IDL.Func(
      [],
      [IDL.Vec(PlayerSpriteConfig)],
      ['query'],
    ),
  'getPurchases' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'getRegionConfigs' : IDL.Func([], [IDL.Vec(RegionConfig)], ['query']),
  'getSessionState' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'activeSpells' : IDL.Vec(IDL.Nat),
            'covenantBuff' : IDL.Text,
            'shrineCount' : IDL.Nat,
            'bloodBalance' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getShopPackages' : IDL.Func([], [IDL.Vec(ShopPackage)], ['query']),
  'getShopPaymentLinks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getSpellConfigs' : IDL.Func([], [IDL.Vec(SpellConfig)], ['query']),
  'getTierSpawnConfig' : IDL.Func([], [TierSpawnConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [IDL.Text], []),
  'getUserUiLayout' : IDL.Func([], [IDL.Text], ['query']),
  'initDefaultNames' : IDL.Func([], [], []),
  'initiatePurchase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPlayerBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'markAchievementUnlocked' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markChangelogShown' : IDL.Func([IDL.Text], [], []),
  'processPendingPurchases' : IDL.Func([], [IDL.Nat], []),
  'purchaseBuff' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
      [],
    ),
  'renameCharacter' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetBossRush' : IDL.Func([IDL.Nat], [], []),
  'resetDungeonChain' : IDL.Func([IDL.Principal], [], []),
  'saveActiveSpells' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveBattleStats' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Nat),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveKillCount' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveUserUiLayout' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setAppVersion' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBossConfig' : IDL.Func(
      [BossConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBossPortalAssignment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBossRushProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setChangelog' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setShopPaymentLink' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSpellBarOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unbanPlayer' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unbanPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCharacter' : IDL.Func(
      [IDL.Nat, Character],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateDungeonProgress' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateSessionState' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'upgradeSpell' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'useBuffItem' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerCountry' : IDL.Text,
    'dokaAmount' : IDL.Nat,
    'customerSurname' : IDL.Text,
    'customerPostal' : IDL.Text,
    'customerAddress' : IDL.Text,
    'proofFileUrl' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'customerEmail' : IDL.Text,
    'packageId' : IDL.Text,
    'customerCity' : IDL.Text,
  });
  const AchievementConfig = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'dokaReward' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const EnemyConfig = IDL.Record({
    'ap' : IDL.Nat,
    'hp' : IDL.Nat,
    'id' : IDL.Text,
    'mp' : IDL.Nat,
    'levelMax' : IDL.Nat,
    'levelMin' : IDL.Nat,
    'name' : IDL.Text,
    'initStat' : IDL.Nat,
    'spriteUrl' : IDL.Opt(IDL.Text),
    'regions' : IDL.Vec(IDL.Text),
  });
  const AdminGameConfig = IDL.Record({
    'leaderBoostPercent' : IDL.Nat,
    'dokaSpawnBaseValue' : IDL.Nat,
    'dokaSpawnChance' : IDL.Nat,
  });
  const LevelUpConfig = IDL.Record({
    'spellLevelingCostMultiplier' : IDL.Float64,
    'spellLevelingBaseCost' : IDL.Nat,
    'spellFailBaseChance' : IDL.Float64,
    'maxSpellRange' : IDL.Nat,
    'spellFailReductionPerLevel' : IDL.Float64,
    'spellRangeGrowthLevels' : IDL.Nat,
    'statGrowthPercent' : IDL.Nat,
    'spellDmgGrowthPercent' : IDL.Nat,
    'apMpLevelThreshold' : IDL.Nat,
  });
  const MapModifierConfig = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'modifierType' : IDL.Text,
    'triggerChance' : IDL.Nat,
  });
  const PlayerSpriteConfig = IDL.Record({
    'id' : IDL.Text,
    'rightWalkFrames' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'frontUrl' : IDL.Opt(IDL.Text),
    'frontWalkFrames' : IDL.Vec(IDL.Text),
    'characterPieceType' : IDL.Text,
    'rightUrl' : IDL.Opt(IDL.Text),
    'leftWalkFrames' : IDL.Vec(IDL.Text),
    'backWalkFrames' : IDL.Vec(IDL.Text),
    'leftUrl' : IDL.Opt(IDL.Text),
    'backUrl' : IDL.Opt(IDL.Text),
  });
  const BattleEffect = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'effectType' : IDL.Variant({
      'damage' : IDL.Null,
      'buff' : IDL.Null,
      'debuff' : IDL.Null,
    }),
  });
  const RegionConfig = IDL.Record({
    'id' : IDL.Text,
    'backgroundColor' : IDL.Text,
    'levelMax' : IDL.Nat,
    'levelMin' : IDL.Nat,
    'name' : IDL.Text,
    'battleEffects' : IDL.Vec(BattleEffect),
  });
  const ShopPackage = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'dokaAmount' : IDL.Nat,
    'priceEuroCents' : IDL.Nat,
    'paymentLink' : IDL.Text,
  });
  const SpellConfig = IDL.Record({
    'id' : IDL.Text,
    'aoe' : IDL.Bool,
    'effectCategory' : IDL.Text,
    'damage' : IDL.Nat,
    'lineOfSight' : IDL.Bool,
    'freeCells' : IDL.Bool,
    'effectParams' : IDL.Opt(IDL.Text),
    'mpCost' : IDL.Nat,
    'isPhysical' : IDL.Bool,
    'name' : IDL.Text,
    'hitTiles' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
    'description' : IDL.Text,
    'minLevel' : IDL.Nat,
    'apCost' : IDL.Nat,
    'multiTarget' : IDL.Bool,
    'modifiableRange' : IDL.Bool,
    'usableByEnemy' : IDL.Bool,
    'maxRange' : IDL.Nat,
    'healAmount' : IDL.Nat,
    'iconEmoji' : IDL.Text,
    'hitsAllies' : IDL.Bool,
    'effectType' : IDL.Text,
    'usableByPlayer' : IDL.Bool,
    'spellType' : IDL.Text,
    'diagonal' : IDL.Bool,
    'minRange' : IDL.Nat,
    'range' : IDL.Nat,
    'linear' : IDL.Bool,
    'cooldown' : IDL.Nat,
  });
  const TierSpawnConfig = IDL.Record({
    'adjacentTierPercent' : IDL.Float64,
    'tierSize' : IDL.Nat,
    'sameTierPercent' : IDL.Float64,
    'twoAwayPercent' : IDL.Float64,
    'threeOrMorePercent' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CharacterStats = IDL.Record({
    'ap' : IDL.Nat,
    'hp' : IDL.Nat,
    'mp' : IDL.Nat,
    'sp' : IDL.Nat,
    'sr' : IDL.Nat,
    'atk' : IDL.Nat,
    'chc' : IDL.Nat,
    'res' : IDL.Nat,
    'killCount' : IDL.Nat,
    'init' : IDL.Nat,
    'resilience' : IDL.Nat,
    'evasion' : IDL.Nat,
  });
  const Character = IDL.Record({
    'rotation' : IDL.Nat,
    'activeSpells' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'pieceType' : IDL.Text,
    'name' : IDL.Text,
    'covenantBuff' : IDL.Opt(IDL.Text),
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
    'stats' : CharacterStats,
    'spellLevelKeys' : IDL.Vec(IDL.Text),
    'shrineCount' : IDL.Opt(IDL.Nat),
    'spellLevelValues' : IDL.Vec(IDL.Nat),
    'bloodBalance' : IDL.Opt(IDL.Nat),
    'bossRushMasterComplete' : IDL.Opt(IDL.Bool),
    'colors' : IDL.Vec(IDL.Text),
    'spellBarOrder' : IDL.Opt(IDL.Vec(IDL.Text)),
    'pixelPattern' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const BossStats = IDL.Record({
    'ap' : IDL.Nat,
    'hp' : IDL.Nat,
    'mp' : IDL.Nat,
    'sp' : IDL.Nat,
    'atk' : IDL.Nat,
    'res' : IDL.Nat,
    'init' : IDL.Nat,
  });
  const BossPhaseConfig = IDL.Record({
    'hpThreshold' : IDL.Float64,
    'statMultiplier' : IDL.Float64,
    'phaseNumber' : IDL.Nat,
    'spellPoolIds' : IDL.Vec(IDL.Text),
    'specialAbilities' : IDL.Vec(IDL.Text),
    'summonCount' : IDL.Nat,
  });
  const BossConfig = IDL.Record({
    'id' : IDL.Text,
    'pieceType' : IDL.Text,
    'name' : IDL.Text,
    'portalColor' : IDL.Text,
    'baseStats' : BossStats,
    'rewardXpMultiplier' : IDL.Float64,
    'bossMapColor' : IDL.Text,
    'adminNotes' : IDL.Text,
    'rewardDokaMultiplier' : IDL.Float64,
    'phase1' : BossPhaseConfig,
    'phase2' : BossPhaseConfig,
    'defeated' : IDL.Bool,
  });
  const CharacterSlot = IDL.Opt(Character);
  const CharacterSlots = IDL.Record({
    'slot1' : CharacterSlot,
    'slot2' : CharacterSlot,
    'slot3' : CharacterSlot,
  });
  const BuffInventoryItem = IDL.Record({
    'itemId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const BuffInventory = IDL.Vec(BuffInventoryItem);
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'uiLayout' : IDL.Text });
  const DungeonRecord = IDL.Record({
    'chainDepth' : IDL.Nat,
    'totalMapsCompleted' : IDL.Nat,
    'bestRewardMultiplier' : IDL.Float64,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'colorHex' : IDL.Text,
    'playerName' : IDL.Text,
    'timestampMs' : IDL.Int,
  });
  const AchievementProgress = IDL.Record({
    'achievementId' : IDL.Text,
    'unlockedAt' : IDL.Int,
    'unlocked' : IDL.Bool,
    'claimed' : IDL.Bool,
    'principalId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addEnemyName' : IDL.Func([IDL.Text], [], []),
    'adminAddDoka' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAddDokaToUser' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminBanAccount' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminClearAdBox' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteAchievementConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteEnemyConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteMapModifier' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeletePlayerSpriteConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteRegionConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteShopPackage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteSpellConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetDoka' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'adminGetPurchaseRecords' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRecord), 'err' : IDL.Text })],
        [],
      ),
    'adminGrantDoka' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetAchievementConfig' : IDL.Func(
        [AchievementConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetAdBox' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetBossRushConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetColorPalette' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetEnemyConfig' : IDL.Func(
        [EnemyConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetGameConfig' : IDL.Func(
        [AdminGameConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetLevelUpConfig' : IDL.Func(
        [LevelUpConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetMapModifier' : IDL.Func(
        [MapModifierConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetMapModifierChance' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetPlayerSpriteConfig' : IDL.Func(
        [PlayerSpriteConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetRegionConfig' : IDL.Func(
        [RegionConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetShopPackage' : IDL.Func(
        [ShopPackage],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetSpellConfig' : IDL.Func(
        [SpellConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetTierSpawnConfig' : IDL.Func(
        [TierSpawnConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUnbanAccount' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'applyRewards' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'newLevel' : IDL.Nat,
              'newXp' : IDL.Nat,
              'newDoka' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'banPlayer' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'banPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'calculateAndAwardDoka' : IDL.Func(
        [IDL.Vec(IDL.Record({ 'level' : IDL.Nat }))],
        [IDL.Nat],
        [],
      ),
    'checkAccountStatus' : IDL.Func(
        [],
        [IDL.Record({ 'isBanned' : IDL.Bool })],
        ['query'],
      ),
    'claimAchievementReward' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'completeBossRushRoom' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCharacter' : IDL.Func(
        [IDL.Nat, Character],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBossConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBossPortalAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteCharacter' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteEnemyName' : IDL.Func([IDL.Text], [], []),
    'diagnoseCharacterSlots' : IDL.Func([], [IDL.Text], ['query']),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAchievementConfigs' : IDL.Func(
        [],
        [IDL.Vec(AchievementConfig)],
        ['query'],
      ),
    'getAdBoxes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAllBossConfigs' : IDL.Func([], [IDL.Vec(BossConfig)], ['query']),
    'getAllCharacters' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Principal, CharacterSlots)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getBannedPrincipals' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Principal), 'err' : IDL.Text })],
        ['query'],
      ),
    'getBossConfig' : IDL.Func([IDL.Text], [IDL.Opt(BossConfig)], ['query']),
    'getBossPortalAssignments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getBossRushConfig' : IDL.Func([], [IDL.Text], ['query']),
    'getBossRushState' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getBuffCatalog' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getBuffInventory' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerDokaBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangelog' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getChangelogShownVersion' : IDL.Func(
        [IDL.Principal],
        [IDL.Text],
        ['query'],
      ),
    'getCharacter' : IDL.Func([IDL.Nat], [CharacterSlot], ['query']),
    'getCharacterSlots' : IDL.Func([], [CharacterSlots], ['query']),
    'getCharacterStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : Character, 'err' : IDL.Text })],
        ['query'],
      ),
    'getColorPalette' : IDL.Func([], [IDL.Text], ['query']),
    'getDokaBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDungeonRecord' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DungeonRecord)],
        ['query'],
      ),
    'getEnemyConfigs' : IDL.Func([], [IDL.Vec(EnemyConfig)], ['query']),
    'getEnemyHPForLevel' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getEnemyNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getGameConfig' : IDL.Func([], [AdminGameConfig], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'killCount' : IDL.Nat,
              'level' : IDL.Nat,
              'achievementsCompleted' : IDL.Nat,
              'playerName' : IDL.Text,
              'principalId' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getLevelUpConfig' : IDL.Func([], [LevelUpConfig], ['query']),
    'getMapModifiers' : IDL.Func([], [IDL.Vec(MapModifierConfig)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMyPurchaseHistory' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getPlayerAchievements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AchievementProgress)],
        ['query'],
      ),
    'getPlayerSpriteConfigs' : IDL.Func(
        [],
        [IDL.Vec(PlayerSpriteConfig)],
        ['query'],
      ),
    'getPurchases' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'getRegionConfigs' : IDL.Func([], [IDL.Vec(RegionConfig)], ['query']),
    'getSessionState' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'activeSpells' : IDL.Vec(IDL.Nat),
              'covenantBuff' : IDL.Text,
              'shrineCount' : IDL.Nat,
              'bloodBalance' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getShopPackages' : IDL.Func([], [IDL.Vec(ShopPackage)], ['query']),
    'getShopPaymentLinks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getSpellConfigs' : IDL.Func([], [IDL.Vec(SpellConfig)], ['query']),
    'getTierSpawnConfig' : IDL.Func([], [TierSpawnConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [IDL.Text], []),
    'getUserUiLayout' : IDL.Func([], [IDL.Text], ['query']),
    'initDefaultNames' : IDL.Func([], [], []),
    'initiatePurchase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPlayerBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'markAchievementUnlocked' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markChangelogShown' : IDL.Func([IDL.Text], [], []),
    'processPendingPurchases' : IDL.Func([], [IDL.Nat], []),
    'purchaseBuff' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
        [],
      ),
    'renameCharacter' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetBossRush' : IDL.Func([IDL.Nat], [], []),
    'resetDungeonChain' : IDL.Func([IDL.Principal], [], []),
    'saveActiveSpells' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveBattleStats' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Nat),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveKillCount' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveUserUiLayout' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setAppVersion' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBossConfig' : IDL.Func(
        [BossConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBossPortalAssignment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBossRushProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setChangelog' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setShopPaymentLink' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSpellBarOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unbanPlayer' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unbanPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCharacter' : IDL.Func(
        [IDL.Nat, Character],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateDungeonProgress' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateSessionState' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'upgradeSpell' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'useBuffItem' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : BuffInventory, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };